/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gjkbroadcasts;

import java.awt.Font;
import java.io.FileNotFoundException;
/**
 *
 * @author Jacky
 */
public class SchedulePnl extends javax.swing.JPanel {

    /**
     * Creates new form schedulePnl
     */
    public SchedulePnl() {
        initComponents();
        
        try {
            Club[] clubs = Club.readClubs();
            Club.bubbleSche(clubs);
            String schedule = "<html>";
            for (int i = 0; i < clubs.length; i++) {
                schedule += clubs[i].toString() + "<br/>";
            }
            schedule += "</html>";
            clubLbl.setText(schedule);
        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage() + "\nError Grabbing Clubs");
        }
        clubLbl.setFont(new Font("Segoe UI", Font.BOLD, 16));
        clubLbl.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clubLbl = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(587, 206));

        jLabel1.setText("Schedule");

        clubLbl.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(clubLbl)))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clubLbl)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clubLbl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
