/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gjkbroadcasts;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import javax.swing.ImageIcon;
import twitter4j.Twitter;
import twitter4j.TwitterException;

/**
 *
 * @author Jacky
 */
public class TwitterPnl extends javax.swing.JPanel {
    
        static ImageIcon pfp = new ImageIcon("pfp.jpg");
    static String handle = "ERROR NAME N/A";
    static Twitter twitt;
    /**
     * Creates new form twitterPnl
     */
    public TwitterPnl() {
        initComponents();
        twitterLbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
        twitterLbl.setForeground(Color.white);
        twitterLbl.setIcon(new ImageIcon("twitter.png"));
        //Grabs the twitter keys
        try {
            twitt = TwitterHelper.readKeysLogin();
        } catch (IOException ex) {
            System.out.println("Error Loading Keys Into Program");
        }
        
        //Downloads the profile picture
        pfp = TwitterHelper.grabPfp(twitt);
        //colect the handle of the account
        try{
            handle =  TwitterHelper.getHandle(twitt,"");
        }
        catch (TwitterException e){
            System.out.println(e.getMessage() + "\nError collecting Twitter Handle >:c");            
        }
        try {
            statusLbl.setText(TwitterHelper.readLatest(twitt,""));
        } catch (TwitterException e) {
            System.out.println(e.getMessage() + "\nError collecting Twitter Status >:c");
        }
        pfpLbl.setText("@"+handle);
        pfpLbl.setIcon(pfp);
        
        pfpLbl.setFont(new Font("Segoe UI", Font.BOLD, 16));
        pfpLbl.setForeground(Color.white);
        
        statusLbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
        statusLbl.setForeground(Color.white);
        
        pfpLbl.repaint();
        statusLbl.repaint();        
        twitterLbl.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        twitterLbl = new javax.swing.JLabel();
        pfpLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        atField = new javax.swing.JTextField();
        atBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 51));

        twitterLbl.setBackground(new java.awt.Color(255, 255, 255));
        twitterLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        twitterLbl.setText("Twitter");

        pfpLbl.setBackground(new java.awt.Color(255, 255, 255));
        pfpLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pfpLbl.setText("jLabel2");

        statusLbl.setBackground(new java.awt.Color(255, 255, 255));
        statusLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLbl.setText("jLabel2");

        atField.setText("Fill in account name");

        atBtn.setText("OK!");
        atBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(twitterLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(pfpLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(statusLbl)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twitterLbl)
                    .addComponent(atField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atBtn))
                .addGap(18, 18, 18)
                .addComponent(pfpLbl)
                .addGap(18, 18, 18)
                .addComponent(statusLbl)
                .addContainerGap(363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atBtnActionPerformed
        // TODO add your handling code here:
        //colect the handle of the account
        String handle = atField.getText();
        try {
            handle = TwitterHelper.getHandle(twitt, handle);
        } catch (TwitterException e) {
            System.out.println(e.getMessage() + "\nError collecting Twitter Handle >:c");
        }
        try {
            statusLbl.setText(TwitterHelper.readLatest(twitt, handle));
        } catch (TwitterException e) {
            System.out.println(e.getMessage() + "\nError collecting Twitter Status >:c");
        }

        pfpLbl.setText("@" + handle);
        pfpLbl.repaint();
        statusLbl.repaint();
    }//GEN-LAST:event_atBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atBtn;
    private javax.swing.JTextField atField;
    private javax.swing.JLabel pfpLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel twitterLbl;
    // End of variables declaration//GEN-END:variables
}
